version: '2'
services:
    lb:
        image: nginx
        restart: unless-stopped
        networks:
            txbits:
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./txbitsdocker/lb/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./secrets/webserver-key.pem:/secrets/webserver-key.pem:ro
            - ./secrets/webserver.pem:/secrets/webserver.pem:ro
            - ./secrets/dhparam.pem:/secrets/dhparam.pem:ro
    frontend:
        build:
            context: txbitsdocker
            dockerfile: frontend/Dockerfile
        restart: unless-stopped
        networks:
            txbits:
        env_file:
            - ./common.env
    wallet:
        build: 
            context: txbitsdocker
            dockerfile: frontend/Dockerfile
        restart: unless-stopped
        networks:
            txbits:
        env_file:
            - ./common.env
            - ./wallet.env
        environment:
            - IS_WALLET=true
    memcached:
        image: memcached
        restart: unless-stopped
        networks:
            txbits:
    db:
        image: postgres:9.3
        restart: unless-stopped
        networks:
            txbits:
        volumes:
            - db_data:/data
            - db_data2:/var/lib/postgresql/data
            - ./txbitsdocker/db:/dbinfo:ro
        env_file:
            - ./common.env
    bitcoind:
        build:
            context: txbitsdocker
            dockerfile: bitcoind/Dockerfile
        restart: unless-stopped
        networks:
            txbits:
        env_file:
            - ./common.env
            - ./bitcoind.env
        volumes:
            - bitcoind_data:/data
    litecoind:
        build:
            context: txbitsdocker
            dockerfile: litecoind/Dockerfile
        restart: unless-stopped
        networks:
            txbits:
        env_file:
            - ./common.env
            - ./litecoind.env
        volumes:
            - litecoind_data:/data
networks:
    txbits:
        driver: bridge
volumes:
    litecoind_data:
    bitcoind_data:
    db_data:
    db_data2:
